### ISSUE TITLE
Update to latest formalist form AST, with validation rules removed

### ISSUE THREAD

**Issue by timriley** [icelab/formalist-compose#3]
In https://github.com/icelab/formalist/commit/8fe650bf67787b72c6c7afed8261cd9e9d6cedf7, I removed the dry-validation schema-extracted validation rules (aka "predicate lists") from our AST output.

Specifically, these validation rules params from the AST output have gone:

* 3rd param of `attr` elements
* 4th param of `field` elements
* 3rd param of `many` elements

Validation rules are now provided via a `validation` attribute on `field` and `many` elements.

**Comment by makenosound** [comment]
Fixed in https://github.com/icelab/formalist-compose/commit/d16a351f7d7f9a386e2666a2d174c2465dfb7e8f
